---
title: "Advent8"
author: "Mandy Grawl"
date: "2025-12-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
file <- "Advent8.txt"
lines <- readLines(file)
pts <- do.call(rbind, strsplit(lines, ","))
pts <- matrix(as.numeric(pts), ncol = 3)

n <- nrow(pts)

sqdist <- function(a, b) {
  sum((a - b)^2)
}

pairs <- data.frame(
  dist2 = numeric(),
  i = integer(),
  j = integer()
)

num_pairs <- n * (n - 1) / 2
pairs$dist2 <- numeric(num_pairs)
pairs$i <- integer(num_pairs)
pairs$j <- integer(num_pairs)

idx <- 1
for (i in 1:(n-1)) {
  for (j in (i+1):n) {
    pairs$dist2[idx] <- sqdist(pts[i, ], pts[j, ])
    pairs$i[idx] <- i
    pairs$j[idx] <- j
    idx <- idx + 1
  }
}

pairs <- pairs[order(pairs$dist2), ]
pairs_k <- pairs[1:1000, ]

parent <- 1:n
size <- rep(1, n)

find <- function(x) {
  while (parent[x] != x) {
    parent[x] <- parent[parent[x]]   
    x <- parent[x]
  }
  x
}

union <- function(a, b) {
  ra <- find(a)
  rb <- find(b)
  if (ra == rb) return(FALSE)
  if (size[ra] < size[rb]) {
    ra_tmp <- ra; ra <- rb; rb <- ra_tmp
  }
  parent[rb] <<- ra
  size[ra] <<- size[ra] + size[rb]
  TRUE
}

for (k in 1:nrow(pairs_k)) {
  union(pairs_k$i[k], pairs_k$j[k])
}

roots <- sapply(1:n, find)
comp_sizes <- sort(table(roots), decreasing = TRUE)

top3 <- as.numeric(comp_sizes[1:3])
answer <- prod(top3)

answer
```
```{r}
sqdist <- function(a, b) {
  sum((a - b)^2)
}

num_pairs <- n * (n - 1) / 2
dist2 <- numeric(num_pairs)
i_idx <- integer(num_pairs)
j_idx <- integer(num_pairs)

k <- 1
for (i in 1:(n-1)) {
  for (j in (i+1):n) {
    dist2[k] <- sqdist(pts[i,], pts[j,])
    i_idx[k] <- i
    j_idx[k] <- j
    k <- k + 1
  }
}

ord <- order(dist2)
dist2 <- dist2[ord]
i_idx <- i_idx[ord]
j_idx <- j_idx[ord]

parent <- 1:n
size <- rep(1, n)

find <- function(x) {
  while (parent[x] != x) {
    parent[x] <- parent[parent[x]]
    x <- parent[x]
  }
  x
}

union <- function(a, b) {
  ra <- find(a)
  rb <- find(b)
  if (ra == rb) return(FALSE)
  if (size[ra] < size[rb]) {
    tmp <- ra; ra <- rb; rb <- tmp
  }
  parent[rb] <<- ra
  size[ra] <<- size[ra] + size[rb]
  TRUE
}

components <- n
last_i <- last_j <- NA

for (k in seq_len(num_pairs)) {
  a <- i_idx[k]
  b <- j_idx[k]
  if (union(a, b)) {
    components <- components - 1
    last_i <- a
    last_j <- b
    if (components == 1) break
  }
}

X1 <- pts[last_i, 1]
X2 <- pts[last_j, 1]
answer <- X1 * X2

answer
```

