---
title: "Advent3"
author: "Mandy Grawl"
date: "2025-12-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
banks <- readLines("Advent3.txt")

max_joltage <- function(s) {
  digits <- as.integer(strsplit(s, "")[[1]])
  n <- length(digits)
  best <- -Inf

  for (i in 1:(n-1)) {
    for (j in (i+1):n) {
      val <- digits[i] * 10 + digits[j]
      if (val > best) best <- val
    }
  }
  
  return(best)
}

bank_values <- sapply(banks, max_joltage)

sum(bank_values)

```

```{r}
max_k_from_bank <- function(s, k = 12) {
  digits <- as.integer(strsplit(s, "")[[1]])
  n <- length(digits)
  if (k > n) stop("")
  
  res_digits <- integer(k)
  start <- 1
  
  for (pos in seq_len(k)) {
    end_idx <- n - (k - pos)
    seg <- digits[start:end_idx]
    maxval <- max(seg)
    rel_idx <- which(seg == maxval)[1]
    res_digits[pos] <- maxval
    start <- start + rel_idx
  }
  
  as.numeric(paste(res_digits, collapse = ""))
}

bank_values <- vapply(banks, max_k_from_bank, numeric(1), k = 12)

sum(bank_values)

```


