---
title: "Advent2"
author: "Mandy Grawl"
date: "2025-12-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
generate_doubles <- function(max_val) {
  candidates <- c()

  max_digits <- nchar(as.character(max_val))
  for (d in seq(2, max_digits, by = 2)) {
    half <- d / 2
    lower <- 10^(half - 1)
    upper <- 10^half - 1

    for (x in lower:upper) {
      doubled <- as.numeric(paste0(x, x))
      candidates <- c(candidates, doubled)
    }
  }

  sort(unique(candidates))
}

input <- "269351-363914,180-254,79-106,771-1061,4780775-4976839,7568-10237,
33329-46781,127083410-127183480,19624-26384,9393862801-9393974421,
2144-3002,922397-1093053,39-55,2173488366-2173540399,879765-909760,
85099621-85259580,2-16,796214-878478,163241-234234,93853262-94049189,
416472-519164,77197-98043,17-27,88534636-88694588,57-76,
193139610-193243344,53458904-53583295,4674629752-4674660925,
4423378-4482184,570401-735018,280-392,4545446473-4545461510,
462-664,5092-7032,26156828-26366132,10296-12941,61640-74898,
7171671518-7171766360,3433355031-3433496616"

ranges <- do.call(rbind, strsplit(input, ","))
ranges <- ranges[!is.na(ranges)]
ranges <- data.frame(
  start = as.numeric(sub("-.*", "", ranges)),
  end   = as.numeric(sub(".*-", "", ranges))
)

max_end <- max(ranges$end)
double_ids <- generate_doubles(max_end)

library(fastmatch)

in_range <- function(x) {
  any(x >= ranges$start & x <= ranges$end)
}

valid_doubles <- double_ids[sapply(double_ids, in_range)]

sum(valid_doubles)


```
```{r}
generate_repeated_patterns <- function(max_val) {
  max_digits <- nchar(as.character(max_val))
  results <- c()

  for (L in 2:max_digits) {              
    for (k in 2:L) {                     
      if (L %% k != 0) next             
      p <- L / k                        
      if (p < 1) next

      lower <- 10^(p-1)                 
      upper <- 10^p - 1

      for (x in lower:upper) {
        num <- as.numeric(paste(rep(x, k), collapse=""))
        results <- c(results, num)
      }
    }
  }

  sort(unique(results))
}

ranges_raw <- unlist(strsplit(input, ","))
ranges <- data.frame(
  start = as.numeric(sub("-.*", "", ranges_raw)),
  end   = as.numeric(sub(".*-", "", ranges_raw))
)

max_end <- max(ranges$end)
candidates <- generate_repeated_patterns(max_end)

library(fastmatch)

in_any_range <- function(x) {
  any(x >= ranges$start & x <= ranges$end)
}

invalid_ids <- candidates[sapply(candidates, in_any_range)]

sum(invalid_ids)

```

